### PR TITLE
Fixed #13 - Hide the browser's address bar and footer on mobile

### LINKED ISSUE #13: Hide the browser's address bar and footer on mobile
Currently when opening the site on mobile, the address bar and footer navigation are visible, taking up a lot of space, especially on small devices.

### PR DESCRIPTION
**Pull request by coreyjjames**
Added meta data and manifest.json to index.html. The meta data controls IOS and manifest for android browsers. I only tested on IOS.

### CODE REVIEW

**Comment by matronator** [comment]
Great, thanks! :)

**Comment by Suneet-M** [comment]
Actually, this code wouldn't make the web site full screen by default. It needs the user to create a shortcut link on the home screen of the device and then launch it from there.

Go ahead and try launching the site on your mobile.
When it doesn't launch full screen try selecting 'add to home screen' from the browser options. Launch it from the home screen and then it will work.

**Comment by matronator** [comment]
I just noticed this after merging, but I tried searching how to hide it directly in the Safari browser and couldn't find much up to date. Seems like they removed that option in some iOS version, but I'm not sure, since I've seen sites that hide it when switching to landscape.

If it is achievable somehow, I guess I'll re-open #13?

**Comment by coreyjjames** [comment]
It works on my IPhone in safari, also I figured there was no need to hide the address bar and footer in portrait mode since the game doesn’t need the extra space in portrait mode. It’s only set to hide in landscape mode.

I only have an IPhone to test with so, I’m not sure if android works.

**Comment by matronator** [comment]
What model and iOS you have? Because for me (iPhone SE, iOS 12.1) it only works as @Suneet-M has described, when viewing the site via regular browser it doesn't go fullscreen.

**Comment by Suneet-M** [comment]
I don't have an iPhone but at least for android I can say this won't work as required. I believe this would be the same for iOS as well but can't confirm.
I can get it to work but I'll have to add a button for it on the site. I haven't worked with crafty js so I don't know if that matters in this case. But I can code it with pure JS, if you want me to.

**Comment by matronator** [comment]
The same happens on my iPhone as well, I have to make a desktop shortcut to that page to work as intended.
I looked through the Crafty docs and repository and it looks like it doesn't have very good mobile support. So if you can code it in pure JS, that'd be great and much appreciated!

**Comment by Suneet-M** [comment]
Sure, I'm on it. I haven't worked with crafty.js before, so give me a day, I'll figure out how to get a button up and running.

**Pull request merged**
